### ISSUE TITLE
Catboost early stopping

### ISSUE THREAD

**Issue by panas89** [uclamii/model_tuner#109]
Catboost after gridsearch using earlystopping in best hyperparameters there is two hyperparametets that cause an error:
n__iterations and num_boost_rounds cannot both be defined when fitting the best model with ealry stopping

**Comment by lshpaner** [comment]
> Catboost after gridsearch using earlystopping in best hyperparameters there is two hyperparametets that cause an error: n__iterations and num_boost_rounds cannot both be defined when fitting the best model with ealry stopping

Is this the error you are seeing?

```python
Pipeline Steps:

┌──────────────────────┐
│ Step 1: cat          │
│ CatBoostClassifier   │
└──────────────────────┘

  0%|                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lshpaner/Documents/GitHub_Repositories/model_tuner/notebooks/catboosttest.py", line 46, in <module>
    model.grid_search_param_tuning(X, y)
  File "/home/lshpaner/miniconda3/envs/conda_311/lib/python3.11/site-packages/model_tuner/model_tuner_utils.py", line 1083, in grid_search_param_tuning
    clf = self.estimator.set_params(**params).fit(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lshpaner/miniconda3/envs/conda_311/lib/python3.11/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lshpaner/miniconda3/envs/conda_311/lib/python3.11/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/home/lshpaner/miniconda3/envs/conda_311/lib/python3.11/site-packages/catboost/core.py", line 5241, in fit
    _process_synonyms(params)
  File "/home/lshpaner/miniconda3/envs/conda_311/lib/python3.11/site-packages/catboost/core.py", line 1618, in _process_synonyms
    _process_synonyms_groups(params)
  File "/home/lshpaner/miniconda3/envs/conda_311/lib/python3.11/site-packages/catboost/core.py", line 1577, in _process_synonyms_groups
    _process_synonyms_group(['iterations', 'n_estimators', 'num_boost_round', 'num_trees'], params)
  File "/home/lshpaner/miniconda3/envs/conda_311/lib/python3.11/site-packages/catboost/core.py", line 1562, in _process_synonyms_group
    raise CatBoostError('only one of the parameters ' + (', '.join(synonyms)) + ' should be initialized.')
_catboost.CatBoostError: only one of the parameters iterations, n_estimators, num_boost_round, num_trees should be initialized.
```

**Comment by lshpaner** [comment]
We cannot pass both or all the of the below at the same time per the [CatBoost documentation](https://catboost.ai/docs/en/references/training-parameters/)
> For the Python package several parameters have aliases. For example, the --iterations parameter has the following synonyms: `num_boost_round`, `n_estimators`, `num_trees`. Simultaneous usage of different names of one parameter raises an error.
