### ISSUE TITLE
KFold return_metrics model_type not determined

### ISSUE THREAD

**Issue by lshpaner** [uclamii/model_tuner#121]
Broken code for KFold example  $\longrightarrow$ `catboost_kfold.py`

Need to fix:

```python
Traceback (most recent call last):
  File "/home/lshpaner/Documents/GitHub_Repositories/model_tuner/notebooks/catboost_kfold.py", line 51, in <module>
    metrics = model.return_metrics(X, y)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lshpaner/Documents/GitHub_Repositories/model_tuner/src/model_tuner/model_tuner_utils.py", line 866, in return_metrics
    self.return_metrics_kfold(X, y, self.test_model, score)
  File "/home/lshpaner/Documents/GitHub_Repositories/model_tuner/src/model_tuner/model_tuner_utils.py", line 1384, in return_metrics_kfold
    report_model_metrics(test_model, X_test, y_test, threshold),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lshpaner/Documents/GitHub_Repositories/model_tuner/src/model_tuner/model_tuner_utils.py", line 1763, in report_model_metrics
    raise ValueError(
ValueError: The model must have a `model_type` attribute to determine the type.
```

The error occurs in `return_metrics_kfold`:

```bash
ValueError: The `test_model` must have a `model_type` attribute.
```

### Why
This happens because `test_model`, which is `self.test_model` in `return_metrics`, does not have the `model_type` attribute.
 - `self.test_model` is expected to have the `model_type` attribute, but it doesn't.
 - This issue is specific to `kfold=True`, which means the way `self.test_model` is used during k-fold evaluation is likely missing a step where `model_type` is set.

### Fix Plan:

We should:
1.  Validate `self.test_model` before passing it to `return_metrics_kfold`.
2.  Debug the missing `model_type` issue by tracing `self.test_model.`

**Comment by lshpaner** [comment]
Fixed through [latest merge](https://github.com/uclamii/model_tuner/pull/128)
